// This file was auto-generated by ML.NET Model Builder. 
using Microsoft.ML;
using Microsoft.ML.Data;
using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
namespace WebApplication4
{
    public partial class CustomerChurnML
    {
        /// <summary>
        /// model input class for CustomerChurnML.
        /// </summary>
        #region model input class
        public class ModelInput
        {
            [ColumnName(@"CreditScore")]
            public float CreditScore { get; set; }

            [ColumnName(@"Geography")]
            public string Geography { get; set; }

            [ColumnName(@"Gender")]
            public string Gender { get; set; }

            [ColumnName(@"Age")]
            public float Age { get; set; }

            [ColumnName(@"Tenure")]
            public float Tenure { get; set; }

            [ColumnName(@"NumOfProducts")]
            public float NumOfProducts { get; set; }

            [ColumnName(@"HasCrCard")]
            public float HasCrCard { get; set; }

            [ColumnName(@"IsActiveMember")]
            public float IsActiveMember { get; set; }

            [ColumnName(@"EstimatedSalary")]
            public float EstimatedSalary { get; set; }

            [ColumnName(@"Exited")]
            public float Exited { get; set; }

        }

        #endregion

        /// <summary>
        /// model output class for CustomerChurnML.
        /// </summary>
        #region model output class
        public class ModelOutput
        {
            [ColumnName(@"CreditScore")]
            public float CreditScore { get; set; }

            [ColumnName(@"Geography")]
            public float[] Geography { get; set; }

            [ColumnName(@"Gender")]
            public float[] Gender { get; set; }

            [ColumnName(@"Age")]
            public float Age { get; set; }

            [ColumnName(@"Tenure")]
            public float Tenure { get; set; }

            [ColumnName(@"NumOfProducts")]
            public float NumOfProducts { get; set; }

            [ColumnName(@"HasCrCard")]
            public float HasCrCard { get; set; }

            [ColumnName(@"IsActiveMember")]
            public float IsActiveMember { get; set; }

            [ColumnName(@"EstimatedSalary")]
            public float EstimatedSalary { get; set; }

            [ColumnName(@"Exited")]
            public float Exited { get; set; }

            [ColumnName(@"Features")]
            public float[] Features { get; set; }

            [ColumnName(@"Score")]
            public float Score { get; set; }

        }

        #endregion

        private static string MLNetModelPath = Path.GetFullPath("CustomerChurnML.zip");

        public static readonly Lazy<PredictionEngine<ModelInput, ModelOutput>> PredictEngine = new Lazy<PredictionEngine<ModelInput, ModelOutput>>(() => CreatePredictEngine(), true);

        /// <summary>
        /// Use this method to predict on <see cref="ModelInput"/>.
        /// </summary>
        /// <param name="input">model input.</param>
        /// <returns><seealso cref=" ModelOutput"/></returns>
        public static ModelOutput Predict(ModelInput input)
        {
            var predEngine = PredictEngine.Value;
            return predEngine.Predict(input);
        }

        private static PredictionEngine<ModelInput, ModelOutput> CreatePredictEngine()
        {
            var mlContext = new MLContext();
            ITransformer mlModel = mlContext.Model.Load(MLNetModelPath, out var _);
            return mlContext.Model.CreatePredictionEngine<ModelInput, ModelOutput>(mlModel);
        }
    }
}
