// This file was auto-generated by ML.NET Model Builder. 
using Microsoft.ML;
using Microsoft.ML.Data;
using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
namespace WebApplication4
{
    public partial class DefaultML
    {
        /// <summary>
        /// model input class for DefaultML.
        /// </summary>
        #region model input class
        public class ModelInput
        {
            [ColumnName(@"LIMIT_BAL")]
            public float LIMIT_BAL { get; set; }

            [ColumnName(@"SEX")]
            public string SEX { get; set; }

            [ColumnName(@"EDUCATION")]
            public string EDUCATION { get; set; }

            [ColumnName(@"MARRIAGE")]
            public string MARRIAGE { get; set; }

            [ColumnName(@"AGE")]
            public float AGE { get; set; }

            [ColumnName(@"PAY_0")]
            public float PAY_0 { get; set; }

            [ColumnName(@"PAY_2")]
            public float PAY_2 { get; set; }

            [ColumnName(@"PAY_3")]
            public float PAY_3 { get; set; }

            [ColumnName(@"PAY_4")]
            public float PAY_4 { get; set; }

            [ColumnName(@"PAY_5")]
            public float PAY_5 { get; set; }

            [ColumnName(@"PAY_6")]
            public float PAY_6 { get; set; }

            [ColumnName(@"BILL_AMT1")]
            public float BILL_AMT1 { get; set; }

            [ColumnName(@"BILL_AMT2")]
            public float BILL_AMT2 { get; set; }

            [ColumnName(@"BILL_AMT3")]
            public float BILL_AMT3 { get; set; }

            [ColumnName(@"BILL_AMT4")]
            public float BILL_AMT4 { get; set; }

            [ColumnName(@"BILL_AMT5")]
            public float BILL_AMT5 { get; set; }

            [ColumnName(@"BILL_AMT6")]
            public float BILL_AMT6 { get; set; }

            [ColumnName(@"PAY_AMT1")]
            public float PAY_AMT1 { get; set; }

            [ColumnName(@"PAY_AMT2")]
            public float PAY_AMT2 { get; set; }

            [ColumnName(@"PAY_AMT3")]
            public float PAY_AMT3 { get; set; }

            [ColumnName(@"PAY_AMT4")]
            public float PAY_AMT4 { get; set; }

            [ColumnName(@"PAY_AMT5")]
            public float PAY_AMT5 { get; set; }

            [ColumnName(@"PAY_AMT6")]
            public float PAY_AMT6 { get; set; }

            [ColumnName(@"default.payment.next.month")]
            public float Default_payment_next_month { get; set; }

        }

        #endregion

        /// <summary>
        /// model output class for DefaultML.
        /// </summary>
        #region model output class
        public class ModelOutput
        {
            [ColumnName(@"LIMIT_BAL")]
            public float LIMIT_BAL { get; set; }

            [ColumnName(@"SEX")]
            public float[] SEX { get; set; }

            [ColumnName(@"EDUCATION")]
            public float[] EDUCATION { get; set; }

            [ColumnName(@"MARRIAGE")]
            public float[] MARRIAGE { get; set; }

            [ColumnName(@"AGE")]
            public float AGE { get; set; }

            [ColumnName(@"PAY_0")]
            public float PAY_0 { get; set; }

            [ColumnName(@"PAY_2")]
            public float PAY_2 { get; set; }

            [ColumnName(@"PAY_3")]
            public float PAY_3 { get; set; }

            [ColumnName(@"PAY_4")]
            public float PAY_4 { get; set; }

            [ColumnName(@"PAY_5")]
            public float PAY_5 { get; set; }

            [ColumnName(@"PAY_6")]
            public float PAY_6 { get; set; }

            [ColumnName(@"BILL_AMT1")]
            public float BILL_AMT1 { get; set; }

            [ColumnName(@"BILL_AMT2")]
            public float BILL_AMT2 { get; set; }

            [ColumnName(@"BILL_AMT3")]
            public float BILL_AMT3 { get; set; }

            [ColumnName(@"BILL_AMT4")]
            public float BILL_AMT4 { get; set; }

            [ColumnName(@"BILL_AMT5")]
            public float BILL_AMT5 { get; set; }

            [ColumnName(@"BILL_AMT6")]
            public float BILL_AMT6 { get; set; }

            [ColumnName(@"PAY_AMT1")]
            public float PAY_AMT1 { get; set; }

            [ColumnName(@"PAY_AMT2")]
            public float PAY_AMT2 { get; set; }

            [ColumnName(@"PAY_AMT3")]
            public float PAY_AMT3 { get; set; }

            [ColumnName(@"PAY_AMT4")]
            public float PAY_AMT4 { get; set; }

            [ColumnName(@"PAY_AMT5")]
            public float PAY_AMT5 { get; set; }

            [ColumnName(@"PAY_AMT6")]
            public float PAY_AMT6 { get; set; }

            [ColumnName(@"default.payment.next.month")]
            public float Default_payment_next_month { get; set; }

            [ColumnName(@"Features")]
            public float[] Features { get; set; }

            [ColumnName(@"Score")]
            public float Score { get; set; }

        }

        #endregion

        private static string MLNetModelPath = Path.GetFullPath("DefaultML.zip");

        public static readonly Lazy<PredictionEngine<ModelInput, ModelOutput>> PredictEngine = new Lazy<PredictionEngine<ModelInput, ModelOutput>>(() => CreatePredictEngine(), true);

        /// <summary>
        /// Use this method to predict on <see cref="ModelInput"/>.
        /// </summary>
        /// <param name="input">model input.</param>
        /// <returns><seealso cref=" ModelOutput"/></returns>
        public static ModelOutput Predict(ModelInput input)
        {
            var predEngine = PredictEngine.Value;
            return predEngine.Predict(input);
        }

        private static PredictionEngine<ModelInput, ModelOutput> CreatePredictEngine()
        {
            var mlContext = new MLContext();
            ITransformer mlModel = mlContext.Model.Load(MLNetModelPath, out var _);
            return mlContext.Model.CreatePredictionEngine<ModelInput, ModelOutput>(mlModel);
        }
    }
}
