// This file was auto-generated by ML.NET Model Builder. 
using Microsoft.ML;
using Microsoft.ML.Data;
using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
namespace WebApplication4
{
    public partial class LoanApprovalML
    {
        /// <summary>
        /// model input class for LoanApprovalML.
        /// </summary>
        #region model input class
        public class ModelInput
        {
            [ColumnName(@"Gender")]
            public string Gender { get; set; }

            [ColumnName(@"Married")]
            public bool Married { get; set; }

            [ColumnName(@"Dependents")]
            public float Dependents { get; set; }

            [ColumnName(@"Education")]
            public string Education { get; set; }

            [ColumnName(@"Self_Employed")]
            public bool Self_Employed { get; set; }

            [ColumnName(@"ApplicantIncome")]
            public float ApplicantIncome { get; set; }

            [ColumnName(@"Coapplica0tI0come")]
            public float Coapplica0tI0come { get; set; }

            [ColumnName(@"LoanAmount")]
            public float LoanAmount { get; set; }

            [ColumnName(@"Loan_Amount_Term")]
            public float Loan_Amount_Term { get; set; }

            [ColumnName(@"Propert1_Area")]
            public string Propert1_Area { get; set; }

            [ColumnName(@"Loan_Status")]
            public float Loan_Status { get; set; }

        }

        #endregion

        /// <summary>
        /// model output class for LoanApprovalML.
        /// </summary>
        #region model output class
        public class ModelOutput
        {
            [ColumnName(@"Gender")]
            public float[] Gender { get; set; }

            [ColumnName(@"Married")]
            public float[] Married { get; set; }

            [ColumnName(@"Dependents")]
            public float Dependents { get; set; }

            [ColumnName(@"Education")]
            public float[] Education { get; set; }

            [ColumnName(@"Self_Employed")]
            public float[] Self_Employed { get; set; }

            [ColumnName(@"ApplicantIncome")]
            public float ApplicantIncome { get; set; }

            [ColumnName(@"Coapplica0tI0come")]
            public float Coapplica0tI0come { get; set; }

            [ColumnName(@"LoanAmount")]
            public float LoanAmount { get; set; }

            [ColumnName(@"Loan_Amount_Term")]
            public float Loan_Amount_Term { get; set; }

            [ColumnName(@"Propert1_Area")]
            public float[] Propert1_Area { get; set; }

            [ColumnName(@"Loan_Status")]
            public float Loan_Status { get; set; }

            [ColumnName(@"Features")]
            public float[] Features { get; set; }

            [ColumnName(@"Score")]
            public float Score { get; set; }

        }

        #endregion

        private static string MLNetModelPath = Path.GetFullPath("LoanApprovalML.zip");

        public static readonly Lazy<PredictionEngine<ModelInput, ModelOutput>> PredictEngine = new Lazy<PredictionEngine<ModelInput, ModelOutput>>(() => CreatePredictEngine(), true);

        /// <summary>
        /// Use this method to predict on <see cref="ModelInput"/>.
        /// </summary>
        /// <param name="input">model input.</param>
        /// <returns><seealso cref=" ModelOutput"/></returns>
        public static ModelOutput Predict(ModelInput input)
        {
            var predEngine = PredictEngine.Value;
            return predEngine.Predict(input);
        }

        private static PredictionEngine<ModelInput, ModelOutput> CreatePredictEngine()
        {
            var mlContext = new MLContext();
            ITransformer mlModel = mlContext.Model.Load(MLNetModelPath, out var _);
            return mlContext.Model.CreatePredictionEngine<ModelInput, ModelOutput>(mlModel);
        }
    }
}
